import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import SWRProvider from "@/providers/SWRProvider";
import {AuthProvider} from "@/context/AuthContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AuthProvider> {/* Обгортаємо весь додаток */}
                    {/* Обгортаємо тут, щоб SWR був доступний усім Client Components */}
                    <SWRProvider>
                        {children}
                    </SWRProvider>
                </AuthProvider>
            </body>
        </html>
    )
        ;
}
